included:
- Sources
line_length:
  warning: 250
  error: 300
  ignores_comments: true
function_body_length:
  warning: 250
  error: 300
large_tuple:
  warning: 3
disabled_rules:
  - colon
  - identifier_name
  - type_name
  - cyclomatic_complexity
  - pattern_matching_keywords
  - nesting
